### ISSUE TITLE
net.thucydides.core.webdriver.exceptions.ElementShouldBeVisibleException

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-demos#28]
Getting this error for below method execution

public ListingItem selectListing(int listingNumber) {
        List<WebElementFacade> listingCards = findAll(By.cssSelector(".listing-card:nth-child(" + listingNumber + ")"));
        WebElementFacade listingCard = listingCards.get(0);
        String name = listingCard.findBy(".card-meta-row").getText();

I tried changing identifier but still getting below error

`net.thucydides.core.webdriver.exceptions.ElementShouldBeVisibleException: Timed out after 5 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@35342d2f
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Vikrams-MacBook-Pro.fritz.box', ip: '192.168.178.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_45'
Driver info: driver.version: unknown
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Vikrams-MacBook-Pro.fritz.box', ip: '192.168.178.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_45'
Driver info: driver.version: unknown
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Vikrams-MacBook-Pro.fritz.box', ip: '192.168.178.33', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_45'
Driver info: driver.version: unknown
    at net.thucydides.showcase.cucumber.pages.SearchResultsPage.selectListing(SearchResultsPage.java:44)
    at net.thucydides.showcase.cucumber.steps.serenity.BuyerSteps.selects_listing(BuyerSteps.java:50)
    at net.thucydides.showcase.cucumber.junit.shopping_cart.AddStuffToTheShoppingCartTest.add_a_leather_jacket_to_the_cart(AddStuffToTheShoppingCartTest.java:27)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)`

@YamStranger / @wakaleo  can you please have a look ? I tried with recent release of serenity 1.1.37-rc.5 and cucumber version 1.1.9

thanks,
Vikram

**Comment by vikramvi** [comment]
getDriver().findElement(By.xpath("//div[@class='card-body overflow-hidden']//div[@class='card-meta-row'][1]")).getText();  

This works but below does not

listingCard.findElement(By.xpath("//div[@class='card-body overflow-hidden']//div[@class='card-meta-row'][1]")).getText();

I think calling findElement on WebElementFacade is failing
